#!/bin/bash
# Script para deploy no Railway

echo "🚀 PUMPS - Deploy no Railway"
echo ""
echo "Pré-requisitos:"
echo "1. Estar logado no Railway (railway login)"
echo "2. Ter um projeto criado (railway init)"
echo ""
echo "Próximos passos:"
echo "1. Adicione variáveis de ambiente:"
echo "   railway variables set FLASK_ENV=production"
echo "   railway variables set BINANCE_API_KEY=sua_key"
echo "   railway variables set BINANCE_API_SECRET=seu_secret"
echo "   railway variables set OPENAI_API_KEY=sk-xxx"
echo ""
echo "2. Deploy:"
echo "   railway deploy"
echo ""
echo "3. Ver logs:"
echo "   railway logs"
echo ""
echo "4. Ver URL:"
echo "   railway open"
echo ""
